---
title: "dataviz project"
author: "Tongxin Zhu"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
student_with_firearms <- read_csv("student_firearm.csv")

ggplot(data=student_with_firearms, aes(x=year2015, y=year2009))+
  geom_point(colour="#95B9D6", size=2)+
  geom_abline(slope=1, intercept=0, colour="grey")+
  geom_text(aes(label=State), size = 3)+
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1))+
   labs(title = "Number of U.S. public school students who brought firearms to or possessed \nfirearms at school per 100,000 students enrolled varied dramatically by state",
        subtitle = "The reletive increase and absolute values are higher in the South and Midwest.",
       caption = "Source: U.S. Department of Education, National Center for Education Statistics, 2017.",
       x= "Number of students who did this in school year 2015-16\nper 100,000 students enrolled",
       y= "Number of students who did this in school year 2009-10\nper 100,000 students enrolled")


### Description:
# Points/States above the reference line show a decrease in number of students who did this per 100,000 students enrolled in 2015-16 school year compared to 2009-10 school year while points/states below the line show an increase.
# The reletive increase and absolute values of number of U.S. public school students (12-18) who brought firearms to or possessed firearms at school per 100,000 students enrolled show a worse situation in the South and Midwest.
# Policies and lessons from Washington state (as well as states near original point) might be helpful for other states to improve safety issues.
```



```{r}
teacher_threatened_attacked <- read_csv("teacher_attacked.csv")
teacher_tidy <- 
  gather(teacher_threatened_attacked, key = sex, value = percentage_pt, 2:3)
view(teacher_tidy)


ggplot(data = teacher_tidy)+
  geom_line(mapping = aes(x=year, y=percentage_pt, color=sex))+
  geom_text(mapping=aes(x=year, y=percentage_pt, 
                        label=percentage_pt, vjust=1), size=3)+
  facet_wrap(~type) +
  labs(title = "Percentage of U.S. public school teachers who reported being threatened with \ninjury or physically attacked by a student from school",
        subtitle = "Female teachers reported more physical attack while male teacher reported more threatened \nwith injury.",
       caption = "Source: U.S. Department of Education, National Center for Education Statistics, 2017.",
       y= "% of public school teachers who reported being hurted\n by a student from school during the previous 12 months",
       x= "Year")
  

### Description:
# In general, phycial attack against male teachers is declining at a more stable rate while showing an increasing trend for female teacher.
# The probability of being threatened with injury is dropping at a higher rate for male teachers compared to female teachers.
# Further investigation is needed to see what have contributed to the increase in both types of violence against female teacher from 2005 to 2010 in order to design intervention.
# Schools might need to design different prevention stratagies for male and female teachers.
```



```{r}
library(ggalt)
school_bullying <- read_csv("bullying.csv")
view(school_bullying)


library(ggalt)
ggplot(school_bullying, aes(x=male, xend=female, y=types_of_bullying))+
  geom_segment(aes(x=male, xend=female,
                   y=types_of_bullying, yend=types_of_bullying),
               color="#969696", size=1.5)+
  geom_dumbbell(color="#969696", 
                size_x=3.5, 
                size_xend = 3.5,
                colour_x ="#00bfc4",
                colour_xend = "#f8766d")+
  geom_text(color="black", size=3, hjust=0.5, vjust=1.5,
            aes(x=male, label=male))+
  geom_text(aes(x=female, label=female), 
            color="black", size=3, hjust=0.5,vjust=-1)+
  
  labs(title = "Percentage of students who reported being bullied at\nschool in the U.S.public & private schools by sex, 2017",
       subtitle = "Girls are more likely to report being Exculded from activities on purpose,\nMade fun of, called names, or insulted and Became subject of rumors.",
       x=" % of students ages 12-18 who reported being bullied \nat scholl in the past year",
       y="Types of bullying",
       caption = "Source: U.S. Department of Education, National Center for Education Statistics")

    
  
### Description:
# There are significant gender differences for being Subject of rumors, being Made fun of/called names/insulted, being Excluded from activities on purpose, and being Pushed/shoved/tripped/spit on.
# In general, girls (labeled above points) suffer more from school bulling than boys (labeled below points), particularly in Subject of rumors, Made fun of/called names/insulted, and Excluded from activities on purpose.
# Policymakers and psychological consultants need to be aware of the gender differences when designing emotional supportive activities at schools.
```



```{r}
security <- read_csv("securitymeasure.csv")
view(security)


security_long <-
  gather(security, key = measure, value = pct, 4:11)
security_long$pct<-round(security_long$pct, 1)
View(security_long)


ggplot(security_long,aes(x=measure, y=pct, fill=level))+
  geom_bar(stat = "identity",
           position = "dodge",
           width = 0.75)+
  geom_text(aes(label=pct), size=3,
            position = position_dodge2(width=1))+
  scale_fill_manual(values = c("#fbb4ae",
                               "#b3cde3",
                               "#ccebc5"))+
  coord_flip()+
  labs(title = "Percentage of U.S. public schools with various safety\nand security measures, by school levels: 2015-16",
       subtitle = "Safety and security measures used by U.S. public schools differ\nacross school levels.",
       caption = "Source: U.S. Department of Education, National Center for Education Statistics",
       y = "Percent of usage",
       x = "Safety and Security Measures")
 

### Description:
# In general, higher-level schools tend to require more students to wear badges/photo ID and less faculty/staff to wear badges/photo ID. 
# However, the percentage of required badges/photo ID for faculty/staff is much higher than that for students in every single school level. As school levels going up, schools are less likely to require school uniforms but still able to enforce a generally strict dress code. 
# Meanwhile, random dog sniffs for drug and random sweeps for contraband are more frequently-used by higher school levels.
# According to the previous visualization, more attention should be put on weapons control.

```


